### ISSUE TITLE
Namespaced variable names

### ISSUE THREAD

**Issue by russelporosky** [HoangTuan110/subreply-css#3]
Using common words can cause conflicts with CSS properties defined in other projects at the same level. `small` for example, refers to slightly smaller text in your CSS, but in my project I might be using `small` as a screen size or max width.

I'd suggest coming up with a short prefix to use on your variables to prevent issues like this; `--surc-small` for example.

**Comment by tsklxiv** [comment]
This has been fixed in pull request #4
